# Default values for helm-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

angularResume:
  # Names
  nameOverride: "angular-resume"
  fullnameOverride: "angular-resume"

  # Force redeployment
  forceRedeployment: true

  # Replicas
  replicaCount: 1

  # Images
  image:
    repository: europe-west9-docker.pkg.dev/back-resume/resume-repository/angular-resume
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "latest"

  ingress:
    className: nginx
    path: "/angular-resume"

  certificate:
    issuerName: letsencrypt-production

  configMap:
    backResumeUrl: "https://clement.duployez.fr/back-resume"

  # Service
  service:
    http:
      name: http
      port: 80
    https:
      name: https
      port: 443
    containerPort: 80

  # Host
  host: clement.duployez.fr

  # Resources
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
      ephemeral_storage: 128Mi
    limits:
      cpu: 100m
      memory: 128Mi
      ephemeral_storage: 128Mi

  # Autoscaling
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 2
    targetCPUUtilizationPercentage: 80







