export enum SkillEnum {
    JAVA = 'java',
    SPRING = 'spring',
    C_PLUS_PLUS = 'cplusplus',
    C_SHARP = 'csharp',
    ANGULAR = 'angular',
    PYTHON = 'python',
    ANDROID = 'android',
    HTML = 'html',
    CSS = 'css',
    JAVASCRIPT = 'javascript',
    TYPESCRIPT = 'typescript',
    KEYCLOAK = 'keycloak',
    MYSQL = 'mysql',
    MONGODB = 'mongodb',
    MAVEN = 'maven',
    GIT = 'git',
    LINUX = 'linux',
    DOCKER = 'docker'
}
